version: '3'
services:
  db:
    image: mysql:8
    ports:
      - 8080:8080
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=mydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./src/migration/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - my-network
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data:
